### ISSUE TITLE
Bug: Tables without final newline

### ISSUE THREAD

**Issue by yaycmyk** [wooorm/remark#123] opened 2016-01-04 15:56 UTC
`remark.parse("|foo|bar|\n|-|-|\n|1|2|")` results in mdast with the following shape:

```
{
    type: 'root',
    children: [
        {
            type: 'table',
            align: [
                null,
                null
            ],
            children: [
                {
                    type: 'tableHeader',
                    children: [
                        Object
                    ]
                }
            ]
        },
        {
            type: 'paragraph',
            children: [
                {
                    type: 'text',
                    value: '|1|2|',
                    position: [
                        Object
                    ]
                }
            ]
        }
    ]
}
```

(I took out the position objects to make the above more concise.)

For some reason the row is being pulled out as a paragraph now. I see there are some new table options added to the parse configuration object and toyed with them, but neither seems to fix the issue.

Parsing the above string definitely worked in the 2.x tree.

**Comment by wooorm** [comment] 2016-01-05 08:51
I think [3.1.3](https://github.com/wooorm/remark/releases/tag/3.1.3) closed this. I got these results with the aforementioned example:

```json
{
  "type": "root",
  "children": [
    {
      "type": "table",
      "align": [
        null,
        null
      ],
      "children": [
        {
          "type": "tableHeader",
          "children": [
            {
              "type": "tableCell",
              "children": [
                {
                  "type": "text",
                  "value": "foo"
                }
              ]
            },
            {
              "type": "tableCell",
              "children": [
                {
                  "type": "text",
                  "value": "bar"
                }
              ]
            }
          ]
        },
        {
          "type": "tableRow",
          "children": [
            {
              "type": "tableCell",
              "children": [
                {
                  "type": "text",
                  "value": "1"
                }
              ]
            },
            {
              "type": "tableCell",
              "children": [
                {
                  "type": "text",
                  "value": "2"
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}
```

**Comment by yaycmyk** [comment] 2016-01-05 13:32
3.1.3 was installed when I tried it :/

**Comment by wooorm** [comment] 2016-01-05 14:00
Then I’m guessing the problem is the missing EOF EOL, I’ll check.

**Comment by yaycmyk** [comment] 2016-01-05 15:12
@wooorm You're right, it works if I add another newline to the end of the string. Is there a way to overcome the need for it?

**Comment by yaycmyk** [comment] 2016-01-05 18:16
:tada: thanks!

**Closed** 2016-01-05 18:15 UTC

**Comment by wooorm** [comment] 2016-01-05 18:20
No problem, thanks for reporting! :smile:
